src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>Task</label>
    <language>en_US</language>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this task blocked for some reason?</inlineHelpText>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>IF( OR($User.UIThemeDisplayed == &quot;Theme4d&quot;, $User.UIThemeDisplayed == &quot;Theme4t&quot;),
        HYPERLINK(&apos;one.app?source=aloha#/sObject/&apos; + Project_Milestone__r.Project__c + &apos;/view&apos;,
                  Project_Milestone__r.Project__r.Name,
                  &apos;_self&apos;),
        HYPERLINK(Project_Milestone__r.Project__c,
                  Project_Milestone__r.Project__r.Name,
                  &apos;_self&apos;)
   )</formula>
    <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Milestone1_TaskTableController.cls
/** * File Name: Milestone1_TaskTableController.apxc
* Description : Controller for c:mytasks Lightning Component
* Copyright : salesforce.com, Inc. (c) 2016
* * @author : Shae Selix
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 

public with sharing class Milestone1_TaskTableController {
    
    @AuraEnabled
    public static List<Milestone1_Task__c> getIncompletedTasks() {
        Map<DescribeSObjectResult, Set<String>> fieldsToCheck = 
            new Map<DescribeSObjectResult, Set<String>>();
        fieldsToCheck.put(Milestone1_Task__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name', 'due_date__c', 'assigned_to__c', 'complete__c'});
        fieldsToCheck.put(Milestone1_Milestone__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name'});
        fieldsToCheck.put(Milestone1_Project__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name', 'status__c'});
        
        Boolean userCanAccess = true;
        for (DescribeSObjectResult dfr : fieldsToCheck.keyset()) {
            if (!Milestone1_Security_Utility.fieldsAllAccess(dfr, fieldsToCheck.get(dfr))) {
                userCanAccess = false;
            }
        }
        
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        
        if (userCanAccess) {
            Id uid = UserInfo.getUserId();
        	tasks = [SELECT Id, Name, Due_Date__c,
                	   Project_Milestone__c, Project_Milestone__r.Name, 
                	   Project_Milestone__r.Project__c,
                       Project_Milestone__r.Project__r.Name
                FROM Milestone1_Task__c
                WHERE Assigned_To__c = :uid
                AND Complete__c = false
                AND Project_Milestone__r.Project__r.Status__c = 'Active'
                ORDER BY Project_Milestone__r.Project__r.Name,
                         Project_Milestone__r.Name,
                         Due_Date__c
                LIMIT 50];
        }
        
        return tasks;
        
        
    }
    
    @AuraEnabled
    public static List<Milestone1_Task__c> getLateTasks() {
        
        Map<DescribeSObjectResult, Set<String>> fieldsToCheck = 
            new Map<DescribeSObjectResult, Set<String>>();
        fieldsToCheck.put(Milestone1_Task__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name', 'due_date__c', 'assigned_to__c', 'complete__c'});
        fieldsToCheck.put(Milestone1_Milestone__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name'});
        fieldsToCheck.put(Milestone1_Project__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name'});
        
        Boolean userCanAccess = true;
        for (DescribeSObjectResult dfr : fieldsToCheck.keyset()) {
            if (!Milestone1_Security_Utility.fieldsAllAccess(dfr, fieldsToCheck.get(dfr))) {
                userCanAccess = false;
            }
        }
        
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        
        if (userCanAccess) {
            Id uid = UserInfo.getUserId();
        	Date td = Date.today();
        	tasks = [SELECT Id, Name, Due_Date__c,
                	   Project_Milestone__c, Project_Milestone__r.Name, 
                	   Project_Milestone__r.Project__c,
                       Project_Milestone__r.Project__r.Name
                FROM Milestone1_Task__c
                WHERE Assigned_To__c = :uid
                AND Complete__c = false
                AND Due_Date__c < :td
                ORDER BY Due_Date__c
                LIMIT 50];
        }
        
        return tasks;
    }
    
    @AuraEnabled
    public static List<Milestone1_Task__c> getBlockedTasks() {
        
        Map<DescribeSObjectResult, Set<String>> fieldsToCheck = 
            new Map<DescribeSObjectResult, Set<String>>();
        fieldsToCheck.put(Milestone1_Task__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name', 'due_date__c', 'assigned_to__c', 'blocked__c'});
        fieldsToCheck.put(Milestone1_Milestone__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name'});
        fieldsToCheck.put(Milestone1_Project__c.sObjectType.getDescribe(),
                          new Set<String>{'id', 'name'});
        
        Boolean userCanAccess = true;
        for (DescribeSObjectResult dfr : fieldsToCheck.keyset()) {
            if (!Milestone1_Security_Utility.fieldsAllAccess(dfr, fieldsToCheck.get(dfr))) {
                userCanAccess = false;
            }
        }
        
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        
        if (userCanAccess) {
            Id uid = UserInfo.getUserId();
        	tasks = [SELECT Id, Name, Due_Date__c,
                	   Project_Milestone__c, Project_Milestone__r.Name, 
                	   Project_Milestone__r.Project__c,
                       Project_Milestone__r.Project__r.Name
                FROM Milestone1_Task__c
                WHERE Assigned_To__c = :uid
                AND Blocked__c = true
                ORDER BY Project_Milestone__r.Project__r.Name,
                         Project_Milestone__r.Name,
                         Due_Date__c
                LIMIT 50];
        }
        
        return tasks;
    }

}