src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias for a milestone.</description>
        <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
        <label>Milestone Alias</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Milestone1: This custom setting allows users to follow tasks automatically assigned to them.</description>
    <fields>
        <fullName>Auto_Follow_Complete_Task__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a Task is marked &apos;Complete&apos;, Automatically unsubscribe the Assigned User from the Chatter Feed for the Task.</description>
        <inlineHelpText>When a Task is marked &apos;Complete&apos;, Automatically unsubscribe the Assigned User from the Chatter Feed for the Task.</inlineHelpText>
        <label>Auto UnFollow A Complete Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Follow_Task__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a Task is Assigned to a User, automatically subscribe the user to follow the task.</description>
        <inlineHelpText>When a Task is Assigned to a User, automatically subscribe the user to follow the task.</inlineHelpText>
        <label>Auto Follow A Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Unfollow_Reassignment__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Automatically unsubscribe the currently assigned user from the task when it is reassigned to another user.</inlineHelpText>
        <label>Auto Unfollow Reassignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Report_Id_Blocked_Tasks_by_Project__c</fullName>
        <label>Report Id: Blocked Tasks by Project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_My_Blocked_Tasks__c</fullName>
        <label>Report Id: My Blocked Tasks</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_My_Late_Tasks__c</fullName>
        <label>Report Id: My Late Tasks</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_My_Tasks_By_Priority_Project__c</fullName>
        <label>Report Id: My Tasks By Priority, Project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_My_Tasks_By_Project_Milesto__c</fullName>
        <label>Report Id: My Tasks By Project + Milesto</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_My_tasks_by_project__c</fullName>
        <inlineHelpText>Report to use for showing my tasks by project.  pv0 = project id (15 char) and pv1 = Assign to name.</inlineHelpText>
        <label>Report Id: My tasks by project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_Open_Task_Status_by_Project__c</fullName>
        <label>Report Id: Open Task Status by Project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_Overdue_Tasks_by_Project__c</fullName>
        <label>Report Id: Overdue Tasks by Project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_Project_Milestone_Open_Task__c</fullName>
        <label>Report Id: Project, Milestone, Open Task</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Id_Task_Status_By_Project__c</fullName>
        <label>Report Id: Task Status By Project</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Milestone1 Settings</label>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>Task</label>
    <language>en_US</language>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this task blocked for some reason?</inlineHelpText>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <inlineHelpText>If blocked, why?</inlineHelpText>
    <label>Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>This is the priority of the task. 0,1,2,3 or 4.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>IF( OR($User.UIThemeDisplayed == &quot;Theme4d&quot;, $User.UIThemeDisplayed == &quot;Theme4t&quot;),
        HYPERLINK(&apos;one.app?source=aloha#/sObject/&apos; + Project_Milestone__r.Project__c + &apos;/view&apos;,
                  Project_Milestone__r.Project__r.Name,
                  &apos;_self&apos;),
        HYPERLINK(Project_Milestone__r.Project__c,
                  Project_Milestone__r.Project__r.Name,
                  &apos;_self&apos;)
   )</formula>
    <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/classes/Milestone1_GettingStartedController.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public with sharing class Milestone1_GettingStartedController {

    public Boolean settingsReady {get;set;}
    public Boolean projectReady {get;set;}
    
    public String lastResult {get;set;}
    
    public Milestone1_GettingStartedController() {
        settingsReady = Milestone1_Settings__c.getOrgDefaults() != null;
        
    }
    
    public void setupStandardSettings() {

        Milestone1_Settings__c settings = Milestone1_Settings__c.getOrgDefaults();
        
        if (settings != null) {
            lastResult = system.label.Milestone1_SettingsAlreadyExistNoChanges;     
        } else {
            settings = getInitialSettingsWithoutSave();
            

            
            insert settings;
            
            settingsReady = true;
            

            handleGettingStartedProjectInitialization();
            
            
        }
        
    }
    
    public Milestone1_Project__c handleGettingStartedProjectInitialization() {

        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        List<Milestone1_Milestone__c> milestones = new List<Milestone1_Milestone__c>();
        
            Milestone1_Project__c project = null;
            

            List<Document> docs = [Select d.Name, d.Id, d.Body From Document d Where d.Name = 'Starter Project (LPM1)'];
            
            if (docs.size() == 1) {
                Document startProject = docs.get(0);
                
                Milestone1_XML_Import_Utility util = new Milestone1_XML_Import_Utility();
                
                project = util.importProject(startProject.body.toString());
                
                
                //now we need to go through and  update the project with start date and deadlines.
                //Milestones
                List<Milestone1_Milestone__c> milestonesRetrieved = [Select m.Name, m.Kickoff__c, m.Id, m.Alias__c, m.Deadline__c, m.Project__c,
                    (Select Id, Name, Blocked_Reason__c, Blocked__c, Complete__c, Due_Date__c, Priority__c, Start_Date__c 
                    From Project_Tasks__r) From Milestone1_Milestone__c m WHERE m.Project__c = :project.id Order By m.Name];
                    
                
                //start day = 3 days ago
                project.Kickoff__c = Date.today().addDays(-5);
                project.Deadline__c = Date.today().addDays(28);
                project.Status__c = 'Active';
                update project;
                
                Integer offset = -4;
                Date max_Deadline_Date = Date.today();
                //milestones
                integer aliasCount = [Select count() from Milestone1_Milestone__c Where Alias__c LIKE 'DEMO_%'];
                for (Milestone1_Milestone__c current : milestonesRetrieved) {
                    aliasCount++;
                    Date max_Due_Date = Date.today();
                    current.Kickoff__c = Date.today().addDays(offset);
                    for (Milestone1_Task__c task : current.Project_Tasks__r) {
                        offset++;   
                        task.Start_Date__c = Date.today().addDays(offset);
                        task.Due_Date__c = Date.today().addDays(offset+1);
                        
                        if (current.Name.startsWith('1')) {
                            task.Complete__c = true;
                        }
                        if (max_Due_Date < task.Due_Date__c){
                            max_Due_Date = task.Due_Date__c;
                        }
                        tasks.add(task);
                    }
                    
                    current.Deadline__c = max_Due_Date;
                    if (current.Name.startsWith('1')) {
                        current.Complete__c = true;
                    }
                    if (current.Deadline__c > max_Deadline_Date){
                        max_Deadline_Date = current.Deadline__c;
                    }
                    
                    //get a unique milestone alias
                    String targetAlias = current.Name.substring(0,1);
                    
                    
                    if (aliasCount > 0) {
                        targetAlias = ''+(aliasCount+1);
                    }
                    current.Alias__c = 'DEMO_' + targetAlias;
                    milestones.add(current);
                }
                
                update tasks;
                update milestones;
                
            }
        
        return project;
    }
    
    
    public Milestone1_Settings__c getInitialSettingsWithoutSave() {
        
            Milestone1_Settings__c settings = new Milestone1_Settings__c();
            
            List<Report> reports = [Select Id, Name from Report Where Name like '%(LPM1)'];
            
            Id blockedTasks;
            Id myTasks;
            Id overdueTasks;
            Id overallTaskStatus;
            Id openTaskStatus;
            Id projMilestones;
            Id reportMyTasksAllProjects;
            Id reportMyTasksByPriority;
            Id summaryBlockedTasks;
            Id summaryLateTasks;
            
            
            //these change from install to install so we have to update in settings
            for (Report current : reports) {
                System.debug(current.name);
                if (current.name.indexOf('Blocked Tasks by Project') > -1) {
                    blockedTasks = current.Id;
                } else if (current.name.indexOf('Summary: My Blocked Tasks') > -1) {
                    summaryBlockedTasks = current.Id;
                } else if (current.name.indexOf('Summary: My Late Tasks') > -1) {
                    summaryLateTasks = current.Id;
                } else if (current.name.indexOf('My Incomplete Tasks, By Project') > -1) {
                    reportMyTasksAllProjects = current.id;
                } else if (current.name.indexOf('My Incomplete Tasks, By Priority') > -1) {
                    reportMyTasksByPriority = current.id;
                } else if (current.name.indexOf('My') > -1) {
                    myTasks = current.Id;
                } else if (current.name.indexOf('Overdue') > -1) {
                    overdueTasks = current.Id;
                } else if (current.name.indexOf('Milestones and Open Tasks') > -1) {
                    projMilestones = current.id;
                } else if (current.name.indexOf('Open Tasks') > -1) {
                    openTaskStatus = current.Id;
                } else if (current.name.indexOf('Tasks By Project') > -1) {
                    overallTaskStatus = current.id;
                }
            }
            settings.Report_Id_Blocked_Tasks_by_Project__c = String.valueOf(blockedTasks).substring(0,15);
            settings.Report_Id_My_tasks_by_project__c = String.valueOf(myTasks).substring(0,15);
            settings.Report_Id_Overdue_Tasks_by_Project__c = String.valueOf(overdueTasks).substring(0,15);
            settings.Report_Id_Task_Status_By_Project__c = String.valueOf(overallTaskStatus).substring(0,15);
            settings.Report_Id_Open_Task_Status_by_Project__c = String.valueOf(openTaskStatus).substring(0,15);
            settings.Report_Id_Project_Milestone_Open_Task__c = String.valueOf(projMilestones).substring(0,15);
            settings.Report_Id_My_Tasks_By_Project_Milesto__c = String.valueOf(reportMyTasksAllProjects).substring(0,15);
            settings.Report_Id_My_Tasks_By_Priority_Project__c = String.valueOf(reportMyTasksByPriority).substring(0,15);
            settings.Report_Id_My_Blocked_Tasks__c = String.valueOf(summaryBlockedTasks).substring(0,15);
            settings.Report_Id_My_Late_Tasks__c = String.valueOf(summaryLateTasks).substring(0,15);
            
            settings.Auto_Follow_Task__c = false;
            settings.Auto_Unfollow_Reassignment__c = false;
            settings.Auto_Follow_Complete_Task__c = false;
        
            return settings;
        
    }
    
    static testMethod void testGetSettings() {
        
        Milestone1_GettingStartedController cont = new Milestone1_GettingStartedController();
        
        Milestone1_Settings__c settings = cont.getInitialSettingsWithoutSave();
        
        System.assert(settings.Report_Id_Blocked_Tasks_by_Project__c != null);
        System.assert(settings.Report_Id_My_tasks_by_project__c != null);
        System.assert(settings.Report_Id_Overdue_Tasks_by_Project__c != null);
        System.assert(settings.Report_Id_Task_Status_By_Project__c != null);
        System.assert(settings.Report_Id_Open_Task_Status_by_Project__c != null);
        System.assert(settings.Report_Id_Project_Milestone_Open_Task__c != null);
        System.assert(settings.Report_Id_My_Tasks_By_Project_Milesto__c != null);
        System.assert(settings.Report_Id_My_Tasks_By_Priority_Project__c != null);
        System.assert(settings.Report_Id_My_Blocked_Tasks__c != null);
        System.assert(settings.Report_Id_My_Late_Tasks__c != null);
        
        System.assert(!settings.Auto_Follow_Complete_Task__c);
        System.assert(!settings.Auto_Follow_Task__c);
        System.assert(!settings.Auto_Unfollow_Reassignment__c);
        
    }
    

    static testMethod void testGettingStartedProject() {
        
        Test.startTest();
        
        Milestone1_GettingStartedController cont = new Milestone1_GettingStartedController();
        
        Milestone1_Project__c project = cont.handleGettingStartedProjectInitialization();
        
        System.assert(project != null);
        
        Test.stopTest();
        
    }
}