src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>Task</label>
    <language>en_US</language>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/Milestone1_XML_Import_Predecessor_Tst.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Milestone1_XML_Import_Export_Tst {

    static testMethod void testProjectManyPredecessorMilestonesManyTasks() {
        final Integer NUMBER_OF_MILESTONES = 50;
	    final Integer NUMBER_OF_TASKS = 10;
	    final Integer NUMBER_OF_SUCCESSOR_MILESTONES = 10;
	    final Integer NUMBER_OF_SUCCESSOR_TASKS = 5;
	  	Document doc;
	    String projectXML;
	    
	    //create a project
	    Milestone1_Project__c project = Milestone1_Test_Utility.sampleProjectActive('proj');
	    insert project;
	    
	    //create a many milestones underneath project
	    List<Milestone1_Milestone__c> milestones = Milestone1_Test_Utility.manyMilestones(project, null,NUMBER_OF_MILESTONES).values();
	    
	    //create a many successor milestones linked to the above created milestones.
	    Map<Milestone1_Milestone__c,List<Milestone1_Milestone__c>> successorMilestones=new Map<Milestone1_Milestone__c,List<Milestone1_Milestone__c>>();
	    for(Milestone1_Milestone__c predecessorMilestone:milestones){
	    	List<Milestone1_Milestone__c> successorMilestone = Milestone1_Test_Utility.manyMilestonesPredecessor(project,predecessorMilestone,NUMBER_OF_SUCCESSOR_MILESTONES).values();
	    	successorMilestones.put(predecessorMilestone,successorMilestone);
	    }
	    
	    //create tasks linked to milestones
	    List<Milestone1_Task__c> tasks;
	    for(Milestone1_Milestone__c mile:milestones)
	    	tasks = Milestone1_Test_Utility.manyTasks(mile,NUMBER_OF_TASKS).values();    
	    
	    //create successor tasks linked to the milestones
	    Map<Milestone1_Task__c,List<Milestone1_Task__c>> successorTasks=new Map<Milestone1_Task__c,List<Milestone1_Task__c>>();
	    for(Milestone1_Task__c task:tasks){
	    	List<Milestone1_Task__c> successorTask= Milestone1_Test_Utility.manyTasksPredecessor(task.Project_Milestone__c,task,NUMBER_OF_SUCCESSOR_TASKS).values();
	    	successorTasks.put(task,successorTask);
	    }
    }
    
   
}