src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias for a milestone.</description>
        <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
        <label>Milestone Alias</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the milestone.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The expense budget for the milestone.</inlineHelpText>
        <label>Milestone Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The hours budget for the milestone.</inlineHelpText>
        <label>Milestone Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Predecessor_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The milestone which must be complete before you start this one. The Predecessor Milestone end date must be before the current Milestone start date.</inlineHelpText>
        <label>Predecessor Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Successor Milestones</relationshipLabel>
        <relationshipName>Successor_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Expense_Budget__c</fullName>
        <formula>Expense_Budget__c +  Expense_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as expense budget + expense budget from sub milestones</inlineHelpText>
        <label>Total Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <formula>Hours_Budget__c + Hours_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as hours budget + hours budget from sub milestones</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the project.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Expense_Budget__c</fullName>
        <inlineHelpText>The total expense budget for this project.</inlineHelpText>
        <label>Total Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <inlineHelpText>The total hours budget for this project.</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>Task</label>
    <language>en_US</language>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Estimated_Expense__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Expense__c</fullName>
    <inlineHelpText>The estimated amount of expenses which will be incurred during the task.</inlineHelpText>
    <label>Estimated Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <inlineHelpText>The estimated time to complete the task.</inlineHelpText>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Predecessor_Task__c.field-meta.xml
<CustomField>
    <fullName>Predecessor_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The predecessor task for this task if applicable.</inlineHelpText>
    <label>Predecessor Task</label>
    <lookupFilter>
        <active>true</active>
        <developerName>nf_01IU00000000WpxMAE_00NU0000000IK2lMAG</developerName>
        <filterItems>
            <field>Milestone1_Task__c.Project_Milestone__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Milestone__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Task__c</referenceTo>
    <relationshipLabel>Successor Tasks</relationshipLabel>
    <relationshipName>Successor_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Milestone</label>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/classes/Milestone1_Test_Import_Export.cls
/* 
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.
 
*/
@isTest
private class Milestone1_Test_Import_Export {

    static testMethod void testProjectManyMilestonesManyTasksImportExport() {
         final Integer NUMBER_OF_MILESTONES = 50;
        final Integer NUMBER_OF_TASKS = 5;
        final Integer NUMBER_OF_SUCCESSOR_MILESTONES = 5;
        final Integer NUMBER_OF_SUCCESSOR_TASKS = 3;
        Document doc;
        String projectXML;
        
        //create a project
        Milestone1_Project__c project = Milestone1_Test_Utility.sampleProjectActive('proj');
        insert project;
        
        //create a many milestones underneath project
        List<Milestone1_Milestone__c> milestones = manyMilestones(project, null,NUMBER_OF_MILESTONES);
        
        //create a predecessor milestones Linked to above milestones
        List<Milestone1_Milestone__c> successorMilestones = new List<Milestone1_Milestone__c>();//=manyMilestonesPredecessor(project,milestones[0],NUMBER_OF_SUCCESSOR_MILESTONES);
        Id projectId = project.Id; 
        for(Integer i = 0; i < NUMBER_OF_SUCCESSOR_MILESTONES; i++){
           Milestone1_Milestone__c milestone = Milestone1_Test_Utility.testSampleMilestone(projectId, milestones[0].id, 'ms'+i);
            successorMilestones.add(milestone);
        }
        insert successorMilestones;
        
        
        //create tasks linked to milestones
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        for(Integer i = 0; i < NUMBER_OF_TASKS; i++){
            Id parentMilestoneId = milestones[(Math.random() * milestones.size()).intValue()].Id;
            Milestone1_Task__c taskRec = Milestone1_Test_Utility.sampleTask(parentMilestoneId);
            tasks.add(taskRec);
        }
        insert tasks;
        
        List<Milestone1_Task__c> successorTasks = new List<Milestone1_Task__c>();
        for(Integer i = 0; i < NUMBER_OF_SUCCESSOR_TASKS; i++){
            Id parentMilestoneId = tasks[0].Project_Milestone__c;
            Milestone1_Task__c taskRec = Milestone1_Test_Utility.sampleTask(parentMilestoneId,tasks[0].id,Date.Today().addDays(3),Date.Today().addDays(4));
            successorTasks.add(taskRec);
        }
        insert successorTasks;
        
                
        //create export page controller and call export action
        ApexPages.StandardController stc = new ApexPages.StandardController(project);
        Milestone1_Export_Project_Controller exportProjectController = new Milestone1_Export_Project_Controller(stc);
        exportProjectController.createExportXML();
        doc = exportProjectController.doc;
        projectXML = String.valueOf(doc.Body.toString());  
        
        checkProject(project,projectXML);
        checkMilestones(milestones,projectXML);
        checkTasks(tasks,projectXML);
        
        //make some changes to it 
        modifyProject(project);
        modifyMilestones(milestones);
        modifyTasks(tasks);
        
        //call export action with the new 
        exportProjectController.createExportXML();
        doc = exportProjectController.doc;
        projectXML = String.valueOf(doc.Body.toString());  
        
        // validate
        checkProject(project,projectXML);
        checkMilestones(milestones,projectXML);
        checkSuccessorMilestones(successorMilestones,projectXML);
        checkTasks(tasks,projectXML);
        checkSuccessorTasks(successorTasks,projectXML);
        
        //make some changes to it 
        modifyProject(project);
        modifyMilestones(milestones);
        modifyTasks(tasks);
        
        //delete project 
        stc.delete();
        
        //create import page controller and call import action
        Milestone1_Import_Project_Controller importProjectController = new Milestone1_Import_Project_Controller(null);
        importProjectController.docId = doc.Id;
        importProjectController.importTemplateXML();
        projectXML= importProjectController.getDocumentXMLString();
        
        // validate 
        checkProject(project,projectXML);
        checkMilestones(milestones,projectXML);
        checkSuccessorMilestones(successorMilestones,projectXML);
        checkTasks(tasks,projectXML);
        checkSuccessorTasks(successorTasks,projectXML);
        
    }
    
    /**
    *   Create a batch of milestones
    */
    private static List<Milestone1_Milestone__c> manyMilestones(Milestone1_Project__c project,
                                                                Milestone1_Milestone__c parentMilestone, Integer size){
        Milestone1_Milestone__c milestone;
        List<Milestone1_Milestone__c> milestones = new List<Milestone1_Milestone__c>();
        Id projectId,parentMilestoneId;
        if(project != null){
            projectId = project.Id; 
        }
        if(parentMilestone !=  null){
            parentMilestoneId = milestone.Id;
        }
        for(Integer i = 0; i < size; i++){
            milestone = Milestone1_Test_Utility.sampleMilestone(projectId, parentMilestoneId, 'ms'+i);
            milestones.add(milestone);
        }
        insert milestones;
        return milestones;  
    }
     
   
    
    /**
    *   Check the fields of the project match in the xml.
    */
    private static void checkProject(Milestone1_Project__c project,String xml){
        System.assert(checkField(project,'Id',xml), assertMessage('Id',String.valueOf(project.Id)));
        System.assert(checkField(project,'Total_Hours_Budget__c',xml), assertMessage('Total_Hours_Budget__c',String.valueOf(project.Total_Hours_Budget__c)));
        System.assert(checkField(project,'Total_Expense_Budget__c',xml), assertMessage('Total_Expense_Budget__c',String.valueOf(project.Total_Expense_Budget__c)));
        System.assert(checkField(project,'Status__c',xml), assertMessage('Status__c',String.valueOf(project.Status__c)));
        System.assert(checkField(project,'Description__c',xml), assertMessage('Description__c',String.valueOf(project.Description__c)));
        System.assert(checkField(project,'Name',xml),assertMessage('Name',String.valueOf(project.Name)));       
    }
    
    /**
    *   Check the fields of the milestone match in the xml.
    */
    private static void checkMilestones(List<Milestone1_Milestone__c> milestones,String xml){
        for(Milestone1_Milestone__c milestone : milestones){
            System.assert(checkField(milestone,'Id',xml), assertMessage('Id',String.valueOf(milestone.Id))); 
            System.assert(checkField(milestone,'Description__c',xml), assertMessage('Description__c',String.valueOf(milestone.Description__c))); 
            System.assert(checkField(milestone,'Expense_Budget__c',xml), assertMessage('Expense_Budget__c',String.valueOf(milestone.Expense_Budget__c))); 
            System.assert(checkField(milestone,'Hours_Budget__c',xml), assertMessage('Hours_Budget__c',String.valueOf(milestone.Hours_Budget__c))); 
            System.assert(checkField(milestone,'Name',xml), assertMessage('Name',String.valueOf(milestone.Name))); 
            System.assert(checkField(milestone,'Alias__c',xml), assertMessage('Alias__c',String.valueOf(milestone.Alias__c)));  
        }       
    }
    
    /**
    *   Check the fields of the milestone match in the xml.
    */
    private static void checkSuccessorMilestones(List<Milestone1_Milestone__c> milestones,String xml){
        for(Milestone1_Milestone__c milestone : milestones){
            System.assert(checkField(milestone,'Id',xml), assertMessage('Id',String.valueOf(milestone.Id))); 
            System.assert(checkField(milestone,'Description__c',xml), assertMessage('Description__c',String.valueOf(milestone.Description__c))); 
            System.assert(checkField(milestone,'Kickoff__c',xml), assertMessage('Kickoff__c',String.valueOf(milestone.Kickoff__c))); 
            System.assert(checkField(milestone,'Deadline__c',xml), assertMessage('Deadline__c',String.valueOf(milestone.Deadline__c))); 
            System.assert(checkField(milestone,'Name',xml), assertMessage('Name',String.valueOf(milestone.Name))); 
            System.assert(checkField(milestone,'Predecessor_Milestone__c',xml), assertMessage('Predecessor_Milestone__c',String.valueOf(milestone.Predecessor_Milestone__c)));
            System.assert(checkField(milestone,'Alias__c',xml), assertMessage('Alias__c',String.valueOf(milestone.Alias__c)));  
        }       
    }
    
    /**
    *   Check the fields of the task match in the xml.
    */
    private static void checkTasks(List<Milestone1_Task__c> tasks,String xml){
        for(Milestone1_Task__c task : tasks){
            System.assert(checkField(task,'Id',xml), assertMessage('Id',String.valueOf(task.Id))); 
            System.assert(checkField(task,'Description__c',xml), assertMessage('Description__c',String.valueOf(task.Description__c))); 
            System.assert(checkField(task,'Estimated_Hours__c',xml), assertMessage('Estimated_Hours__c',String.valueOf(task.Estimated_Hours__c))); 
            System.assert(checkField(task,'Estimated_Expense__c',xml), assertMessage('Estimated_Expense__c',String.valueOf(task.Estimated_Expense__c))); 
            System.assert(checkField(task,'Name',xml), assertMessage('Name',String.valueOf(task.Name)));    
        }       
    }
    
     /**
    *   Check the fields of the task match in the xml.
    */
    private static void checkSuccessorTasks(List<Milestone1_Task__c> tasks,String xml){
        for(Milestone1_Task__c task : tasks){
            System.assert(checkField(task,'Id',xml), assertMessage('Id',String.valueOf(task.Id))); 
            System.assert(checkField(task,'Description__c',xml), assertMessage('Description__c',String.valueOf(task.Description__c))); 
            System.assert(checkField(task,'Start_Date__c',xml), assertMessage('Start_Date__c',String.valueOf(task.Start_Date__c))); 
            System.assert(checkField(task,'Due_Date__c',xml), assertMessage('Due_Date__c',String.valueOf(task.Due_Date__c))); 
            System.assert(checkField(task,'Predecessor_Task__c',xml), assertMessage('Predecessor_Task__c',String.valueOf(task.Predecessor_Task__c))); 
            System.assert(checkField(task,'Name',xml), assertMessage('Name',String.valueOf(task.Name)));    
        }       
    }
    
    /**
    *   Modify some fields values in the project
    */
    private static void modifyProject(Milestone1_Project__c project){
        Date today = Date.today();
        project.Description__c = String.valueOf(today);
        project.Name = String.valueOf(today);
        update project;
    }
    
     
    /**
    *   Modify some fields values in the milestones list
    */
    private static void modifyMilestones(List<Milestone1_Milestone__c> milestones){
        Date today = Date.today();
        for(Milestone1_Milestone__c milestone : milestones){
            milestone.Description__c = String.valueOf(today);
            milestone.Name = String.valueOf(today); 
        }
        update milestones;
    }
    
     
    /**
    *   Modify some fields values in the tasks list.
    */
    private static void modifyTasks(List<Milestone1_Task__c> tasks){
        Date today = Date.today();
        for(Milestone1_Task__c task : tasks){
            task.Description__c = String.valueOf(today);
            task.Name = String.valueOf(today);  
        }
        update tasks;
    }
    
    /**
    *   Check if the field value of the Sobject named myObject match in the xml.
    */
    private static Boolean checkField(Sobject myObject,String field,String xml){
        String fieldValue = String.valueOf(myObject.get(field));
        return fieldValue == null || xml.indexOf(EncodingUtil.urlEncode(fieldValue,'UTF-8')) > 0;
    }
    
    /**
    *   Generate an assert message with parameters.
    */
    private static String assertMessage(String param1,String param2){
        if(param2 == null){
            param2 = '';
        }
        return 'error in '+param1+' fieldName with value '+param2;
    }
}